# Generated by Django 5.2.13 on 2026-04-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_banner_alter_color_product_alter_gallery_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('image', 'Image Only'), ('text_overlay', 'Text Overlay'), ('slider', 'Slider Item')], default='image', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Stop displaying after this date', null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Start displaying from this date', null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='text_bg_color',
            field=models.CharField(blank=True, default='rgba(0,0,0,0.6)', help_text='Background color for text (e.g., rgba(0,0,0,0.6) or #000)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='text_position',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('top-left', 'Top Left'), ('top-right', 'Top Right'), ('bottom-left', 'Bottom Left'), ('bottom-right', 'Bottom Right')], default='center', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('danger', 'Danger'), ('success', 'Success'), ('warning', 'Warning'), ('info', 'Info'), ('dark', 'Dark'), ('light', 'Light')], default='primary', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_link',
            field=models.CharField(blank=True, default='/store/shop/', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, default='Shop Now', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[('home', 'Home Page'), ('shop', 'Shop Page'), ('product', 'Product Page'), ('sidebar', 'Sidebar'), ('hero', 'Hero Section'), ('footer', 'Footer Banner')], default='home', max_length=20),
        ),
    ]
