# Generated by Django 5.2.13 on 2026-04-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_banner_banner_type_banner_end_date_banner_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='banner',
            name='banner_type',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='text_bg_color',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='text_position',
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_color',
            field=models.CharField(choices=[('primary', 'Primary'), ('danger', 'Danger'), ('success', 'Success'), ('warning', 'Warning'), ('info', 'Info'), ('dark', 'Dark')], default='primary', max_length=20),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_link',
            field=models.CharField(default='/store/shop/', max_length=500),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(default='Shop Now', max_length=50),
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[('home', 'Home Page'), ('shop', 'Shop Page'), ('product', 'Product Page'), ('sidebar', 'Sidebar')], default='home', max_length=20),
        ),
    ]
